os:
  - linux
  - osx
language: node_js
node_js:
  - 8
  - 10
  - 12
  - 14
  - 15
  - node
  - lts/argon
  - lts/*
  - iojs
after_success:
  - ./node_modules/.bin/istanbul report text-summary lcov
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
services:
  - redis-server
