name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NPM
        run: npm i

      - name: Install grunt
        run: npm install grunt coffeescript

      - name: Grunt Build
        run: npx grunt build
      
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated-index
          path: index.js
